stages:
  - tests
  - deploy

# Install wget, git and composer
before_script:
  - apt-get update && apt-get install wget git -y
  - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php'); unlink('installer.sig');"

php-cs-fixer-7-2:
  image: php:7.2
  stage: tests
  script: |
    php composer.phar install --dev
    php -d memory_limit=-1 vendor/bin/php-cs-fixer fix --dry-run --diff --using-cache=no --diff-format udiff

phpstan-classes-php-7-2:
  image: php:7.2
  stage: tests
  script: |
    php composer.phar install --dev
    php -d memory_limit=-1 vendor/bin/phpstan analyse -c tests/phpstan/phpstan.neon ./ --no-progress --

deploy-artifact-release:
  image: php:7.2
  stage: deploy
  script: |
    php composer.phar install --no-dev -o
    rm .prettyci.composer.json
    rm .php_cs.cache
    rm .php_cs.dist
    rm .gitlab-ci.yml
    rm .editorconfig
    rm -rf .git
    rm .gitignore
    rm -rf tests

  artifacts:
    paths:
    - ./
